version: "3.8"

services:
  fastapi_app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: fastapi_backend_app
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
